# Check on http://lint.travis-ci.org/ after modifying it!  Originally
# modified from https://github.com/biocore/scikit-bio/blob/master/.travis.yml

sudo: false
language: python
env:
  - PYTHON_VERSION=3.6
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - wget http://repo.continuum.io/miniconda/Miniconda3-3.7.3-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda3/bin:$PATH
  # Update conda itself
  - conda update --yes conda
install:
  - conda create --yes -n env_name python=$PYTHON_VERSION --file conda_requirements.txt
  - source activate env_name
  - conda info --envs
  - pip install coverage
  - pip install . --no-deps
script:
  - nosetests --with-coverage
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/9a439713959e710c7971
    on_success: change
    on_failure: always
